<?php

namespace GagneGrosBundle\Repository;

/**
 * CotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotesRepository extends \Doctrine\ORM\EntityRepository
{
}
