<?php

namespace GagneGrosBundle\Repository;

/**
 * ParieurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParieurRepository extends \Doctrine\ORM\EntityRepository
{
}
